keepassxc-browser/background usr/share/webext/keepassxc-browser/
keepassxc-browser/content usr/share/webext/keepassxc-browser/
keepassxc-browser/css usr/share/webext/keepassxc-browser/
# We skip fonts/, we symlink them.
keepassxc-browser/icons usr/share/webext/keepassxc-browser/
keepassxc-browser/_locales usr/share/webext/keepassxc-browser/
keepassxc-browser/options usr/share/webext/keepassxc-browser/
keepassxc-browser/popups usr/share/webext/keepassxc-browser/

# TODO Replace polyfill library
keepassxc-browser/browser-polyfill.min.js usr/share/webext/keepassxc-browser/

keepassxc-browser/global.js usr/share/webext/keepassxc-browser/

# TODO Link instead to the file provided in libjs-jquery package
keepassxc-browser/jquery-3.3.1.min.js usr/share/webext/keepassxc-browser/

keepassxc-browser/manifest.json usr/share/webext/keepassxc-browser/
keepassxc-browser/translate.js usr/share/webext/keepassxc-browser/
