keepassxc-browser/background        usr/share/webext/keepassxc-browser/
debian/missing-sources/nacl-util.js usr/share/webext/keepassxc-browser/background/
debian/missing-sources/browser-polyfill.js usr/share/webext/keepassxc-browser/common/

keepassxc-browser/common   usr/share/webext/keepassxc-browser/
keepassxc-browser/content  usr/share/webext/keepassxc-browser/
keepassxc-browser/css      usr/share/webext/keepassxc-browser/
keepassxc-browser/icons    usr/share/webext/keepassxc-browser/
keepassxc-browser/_locales usr/share/webext/keepassxc-browser/
keepassxc-browser/options  usr/share/webext/keepassxc-browser/
keepassxc-browser/popups   usr/share/webext/keepassxc-browser/

keepassxc-browser/manifest.json usr/share/webext/keepassxc-browser/
